#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
#
export JAVA_HOME="/Library/Java/JavaVirtualMachines/jdk1.7.0_06.jdk/Contents/Home"
export VERTX_HOME="/Users/david/dev/vertx"
export AAU_WORKSPACE="/Users/david/dev/eclipse-workspaces/aau"
export MAVEN_OPTS="-Xmx1G -XX:MaxPermSize=256m"

. ~/.alias
. resty

export PATH="$VERTX_HOME/bin:$JAVA_HOME/bin:$PATH:/Users/david/bin"


export NVM_DIR="/Users/david/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm

#THIS MUST BE AT THE END OF THE FILE FOR GVM TO WORK!!!
[[ -s "/Users/david/.gvm/bin/gvm-init.sh" ]] && source "/Users/david/.gvm/bin/gvm-init.sh"
