#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
#
#export AAU_WORKSPACE="/Users/david/dev/eclipse-workspaces/aau-new"
export AAU_WORKSPACE="/Users/david/work/eclipse-workspaces/lms"
export MAVEN_OPTS="-Xmx1G -XX:MaxPermSize=256m"

export PATH="$HOME/bin:$PATH"
#export PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"
#export MANPATH="/usr/local/opt/coreutils/libexec/gnuman:$MANPATH"
export EDITOR=vim
export VIM_APP_DIR="/usr/local/Cellar/macvim/7.4-104"

. ~/.alias

export NVM_DIR="/Users/david/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm
alias updatenvm='cd "$NVM_DIR" && git pull origin master && git checkout `git describe --abbrev=0 --tags`; source $NVM_DIR/nvm.sh; echo Update complete'

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="/Users/david/.sdkman"
[[ -s "/Users/david/.sdkman/bin/sdkman-init.sh" ]] && source "/Users/david/.sdkman/bin/sdkman-init.sh"
